Repository paketo-buildpacks/maven, pull requests merged in 2022-08, with the labels that each got.

#164 Update Pipeline to 1.25.2
  .github/pipeline-version
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-maven.yml
  .github/workflows/pb-update-mvnd.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#165 Bump go.mod dependencies
  go.mod
  go.sum
Labels: type:dependency-upgrade, semver:patch

#168 Allow setting a maven settings file via an env var
  README.md
  buildpack.toml
  maven/build.go
  maven/build_test.go
Labels: semver:minor, type:enhancement

#174 Implement RFC 0050: Rename Buildpack
  README.md
  buildpack.toml
Labels: type:task, semver:patch
